<?php
/**
 * @file
 * Code for the Bmore Budget Viz module.
 */

/**
 * Implements hook_init().
 */
function bmore_budget_viz_init() {
  // Add D3 & C3 libraries.
  drupal_add_js(libraries_get_path('d3') . '/d3.min.js', array('scope' => 'footer', 'weight' => 0));
  drupal_add_js(libraries_get_path('c3') . '/c3.min.js', array('scope' => 'footer'));
  drupal_add_css(libraries_get_path('c3') . '/c3.min.css');

  // Load the JS to render the visualizations.
  drupal_add_js(drupal_get_path('module', 'bmore_budget_viz') . '/js/viz.js', array('scope' => 'footer'));
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function bmore_budget_viz_ctools_plugin_directory($module, $plugin_type) {
  if ($module == 'ctools' && !empty($plugin_type)) {
    return "plugins/$plugin_type";
  }
}

/**
 * Get Baltimore budget data from Socrata API.
 *
 * @param  string $fiscal_year
 * @return array $viz_data
 */
function bmore_budget_viz_get_data($fiscal_year) {
  $response_data = drupal_static(__FUNCTION__ . '_' . $fiscal_year);

  if (!isset($response_data)) {
    // Info on using API: http://dev.socrata.com/docs/queries.html.
    $data_url = format_string('https://data.baltimorecity.gov/resource/g5wn-pq7y.json?fiscal_year=@fiscal_year&$select=department,sum%28approved_amount%29%20AS%20total&$group=department&$order=total%20DESC&$limit=10', array(
        '@fiscal_year' => $fiscal_year
      )
    );

    $response = drupal_http_request($data_url);

    if ($response->code != 200) {
      if (!empty($response->error)) {
        drupal_set_message(t('Could not load data, Error: @error',
          array('@error' => $response->error)
        ), 'error');
      }

      return null;
    }

    $response_data = json_decode($response->data);
  }

  return $response_data;
}

/**
 * Get bar chart data.
 *
 * Manipulate data from response into format expected
 * by bar chart.
 */
function bmore_budget_viz_get_bar_chart_data($fiscal_year) {
  $response_data = bmore_budget_viz_get_data($fiscal_year);
  $viz_data = array();

  foreach ($response_data as $idx => $response) {
    $department = $response->department;
    $total = $response->total;
    $viz_data['total'][] = $total;
    $viz_data['x'][] = $department;
  }

  return $viz_data;
}

/**
 * Get donut chart data.
 *
 * Manipulate data from response into format expected
 * by donut chart.
 */
function bmore_budget_viz_get_donut_chart_data($fiscal_year) {
  $response_data = bmore_budget_viz_get_data($fiscal_year);
  $viz_data = array();

  foreach ($response_data as $idx => $response) {
    $department = $response->department;
    $total = $response->total;
    $viz_data[$department] = $total;
  }

  return $viz_data;
}
